package com.galandras12.handdroid.ui

// Generated by tools/gen_strings.py - do not edit.
object Languages {
    /** BCP-47 tag to the language's own name. */
    val all: List<Pair<String, String>> = listOf(
        "en" to "English",
        "hu" to "Magyar",
        "de" to "Deutsch",
        "fr" to "Français",
        "es" to "Español",
        "it" to "Italiano",
        "pt" to "Português",
        "pl" to "Polski",
        "ru" to "Русский",
        "tr" to "Türkçe",
        "ja" to "日本語",
        "zh" to "中文",
    )
}
