#!/usr/bin/env python3
"""Runs the command lines generated by CommandBuilderTest against a desktop ffmpeg (sanity check on a 3 s test clip).

    ./gradlew :app:testDebugUnitTest && python3 tools/validate_commands.py app/build/commands.tsv app/build/commands_variants.tsv
"""
import os, subprocess, sys, tempfile

work = tempfile.mkdtemp(prefix="hd_validate_")
src = os.path.join(work, "in.mkv")
# 1280x720 25fps test pattern, 5.1 AC-3 + stereo AAC audio, two SRT subtitle tracks
srt = os.path.join(work, "s.srt")
open(srt, "w").write("1\n00:00:00,000 --> 00:00:01,500\nHello HandDroid\n")
subprocess.run(["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", "testsrc2=size=1280x720:rate=25:duration=3",
                "-f", "lavfi", "-i", "sine=frequency=440:duration=3", "-f", "lavfi", "-i", "sine=frequency=880:duration=3",
                "-i", srt, "-i", srt, "-map", "0:v", "-map", "1:a", "-map", "2:a", "-map", "3:s", "-map", "4:s",
                "-c:v", "libx264", "-c:a:0", "ac3", "-ac:a:0", "6", "-c:a:1", "aac", "-c:s", "srt", src], check=True)

fail = 0
total = 0
for tsv in sys.argv[1:]:
    for line in open(tsv, encoding="utf-8").read().splitlines():
        name, *passes = line.split("\t")
        if "mediacodec" in line:
            print(f"SKIP  {name} (Android MediaCodec)")
            continue
        total += 1
        ext = passes[-1].split("\x1f")[-1].rsplit(".", 1)[-1]
        out = os.path.join(work, "out." + ext)
        ok = True
        for i, p in enumerate(passes):
            args = p.split("\x1f")
            args = [src if a == "in.mkv" else a for a in args]
            args = [out if a.startswith("out.") else a for a in args]
            args = [os.path.join(work, "pass") if a == "/tmp/log" else a for a in args]
            args = [a.replace("/tmp/log", os.path.join(work, "pass")) for a in args]
            try:
                r = subprocess.run(["ffmpeg", "-v", "error", "-nostdin", *args], capture_output=True, text=True, cwd=work, timeout=120)
            except subprocess.TimeoutExpired:
                ok = False
                print(f"FAIL  {name} (pass {i + 1}): timed out")
                break
            if r.returncode != 0:
                ok = False
                print(f"FAIL  {name} (pass {i + 1}): {r.stderr.strip()[:400]}")
                break
        if ok:
            probe = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "stream=codec_name,width,height", "-of", "csv=p=0", out],
                                   capture_output=True, text=True).stdout.split()
            if not probe:
                ok = False; print(f"FAIL  {name}: no output streams")
        if ok:
            print(f"ok    {name}")
        else:
            fail += 1
print(f"\n{total - fail}/{total} commands ran")
sys.exit(1 if fail else 0)
